### ISSUE TITLE
Nice work adding SASS here

### ISSUE THREAD

**Issue by soggybag** [JSitter/heart-disease-predictor-front#1]
I like that you have added SASS here good work. I think I would keep these files in an scss folder rather than side by side with the css files. That way you can deploy the folder of css without the extra files.

**Comment by soggybag** [comment]
I could be missing something. I can't see way your CSS gets compiled?

**Comment by soggybag** [comment]
You can add sass to react by following the guide here: https://facebook.github.io/create-react-app/docs/adding-a-sass-stylesheet

**Comment by JSitter** [comment]
The SASS stylesheets are being compiled with node-sass per the recommendations by Facebook.
